import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/navbar";
import { ThemeProvider } from "@/components/theme-provider"
import Footer from "@/components/custom/footer";
import {cn} from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          inter.className, "flex overflow-y-scroll h-[100dvh] flex-col justify-between"
      )}>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
          >
              <Navbar/>
              {children}
              <Footer/>
          </ThemeProvider>
      </body>
    </html>
  );
}
